language: python
python:
  - '2.7'
install: pip install -r requirements.txt
before_script:
  - psql -c 'create database test_template_maker;' -U postgres
script: PYTHONPATH=. nosetests template_maker_test/ -v --with-coverage --cover-package=template_maker --cover-erase
