"""empty message

Revision ID: 2f941b1e9680
Revises: 1a850f7e0aa6
Create Date: 2015-04-04 03:05:00.315217

"""

# revision identifiers, used by Alembic.
revision = '2f941b1e9680'
down_revision = '1a850f7e0aa6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_placeholder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('placeholder_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document_base.id'], ),
    sa.ForeignKeyConstraint(['placeholder_id'], ['template_placeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_placeholder')
    ### end Alembic commands ###
