"""empty message

Revision ID: 44b77ae3ee69
Revises: 228017954653
Create Date: 2015-03-18 00:42:45.782409

"""

# revision identifiers, used by Alembic.
revision = '44b77ae3ee69'
down_revision = '228017954653'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_base', sa.Column('section_order', postgresql.ARRAY(sa.Integer()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_base', 'section_order')
    ### end Alembic commands ###
