"""Initial Migration -- create base tables

Revision ID: 5549c709cd56
Revises: None
Create Date: 2015-03-07 18:01:52.758223

"""

# revision identifiers, used by Alembic.
revision = '5549c709cd56'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    variable_types = op.create_table('variable_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(variable_types, [
        { 'id': 1, 'type': 'unicode' },
        { 'id': 2, 'type': 'date' },
        { 'id': 3, 'type': 'int' },
        { 'id': 4, 'type': 'float' }
    ])
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('template_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('template_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['template_section.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template_base.id'], ),
    sa.ForeignKeyConstraint(['type'], ['variable_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_section',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['template_section.id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('fixed_text_section',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['template_section.id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixed_text_section')
    op.drop_table('text_section')
    op.drop_table('template_variables')
    op.drop_table('roles')
    op.drop_table('template_section')
    op.drop_table('users')
    op.drop_table('variable_types')
    op.drop_table('template_base')
    ### end Alembic commands ###
